import type { Doc, Id } from "@/convex/_generated/dataModel";
import type { TradeCapture } from "@/lib/review-stats";
import { calculatePnlPreview, calculateRiskReward, calculateStopLossPips } from "@/lib/trade-calculations";

export type QuickLogState = {
  instrument: string;
  direction: "LONG" | "SHORT";
  session: "ASIA" | "LONDON" | "NEW_YORK" | "OTHER";
  environment: "BACKTESTING" | "DEMO" | "LIVE";
  entryPrice: string;
  exitPrice: string;
  stopLossPrice: string;
  positionSize: string;
  commission: string;
  riskAmount: string;
  whyEntered: string;
  winLossStatus: "WIN" | "LOSS" | "BREAK_EVEN";
};

export const REQUIRED_TRADE_FIELDS = ["instrument", "direction", "entryPrice", "stopLossPrice", "riskAmount"];

export function isTradeFormComplete(f: Record<string, unknown>): boolean {
  return REQUIRED_TRADE_FIELDS.every((k) => f[k] && f[k] !== "");
}

export function getDefaultFormState(overrides?: Partial<Record<string, unknown>>): Record<string, unknown> {
  return {
    accountId: "",
    instrument: "EUR/USD",
    direction: "LONG",
    entryPrice: "",
    exitPrice: "",
    positionSize: "0.01",
    commission: "0",
    environment: "DEMO",
    dailyBias: "NEUTRAL",
    externalStructure: "",
    majorLiquidityPools: "",
    internalStructure: "",
    currentRange: "",
    minorPushStatus: "",
    session: "LONDON",
    isInKillzone: true,
    poiType: "EXTREME",
    poiQuality: [],
    poiDescription: "",
    gapSize: "",
    inducementResting: "",
    inducementType: "",
    distanceFromPoi: "",
    liquidityPoolDescription: "",
    cleanBreak: false,
    breakSize: "",
    trapSwept: "NO",
    trapType: "",
    trapLocation: "",
    trapTappedCount: "",
    trapCleanliness: "",
    liquidityEngineering: "",
    liquidityTappedCount: "",
    retailBehavior: "",
    missingInducement: false,
    ltfEntryTimeframe: "5M",
    smcType: "",
    smsAfterTrap: false,
    bmsPattern: "",
    bmsConfidence: "5",
    rtoApplicable: false,
    rtoDistance: "",
    entryConfidence: "5",
    tradeModel: "CONTINUATION",
    narrativeAlignment: true,
    tradingWithMainPush: true,
    noNarrativeMisalignment: true,
    clearLiquidityEngineering: "UNCLEAR",
    institutionsReasoned: false,
    poiMitigationStatus: "UNMITIGATED",
    approachDynamics: "",
    stopLossPrice: "",
    stopLossPlacement: "IFC_ABOVE",
    stopLossPips: "5",
    stopLossQuality: "CLEAN",
    riskAmount: "10",
    riskPercentage: "1",
    target1RR: "3",
    target2RR: "10",
    target1Price: "",
    target2Price: "",
    timeInTradeMinutes: "",
    maxProfitReached: "",
    maxDrawdown: "",
    target1Hit: false,
    target1HitPrice: "",
    stopMovedToBE: false,
    timeToTarget1: "",
    target2Status: "",
    target2ClosedAt: "",
    finalRR: "",
    timeToClose: "",
    breakEvenStopsMoved: false,
    manualExit: false,
    manualExitReason: "",
    manualExitAligned: false,
    tradeClosureReason: "OPEN",
    pnl: "",
    pnlPercentage: "",
    winLossStatus: "BREAK_EVEN",
    tradeQualityScore: "5",
    poiQualityRating: "ACCEPTABLE",
    inducementQualityRating: "CLEAR",
    trinityAlignmentRating: "ACCEPTABLE",
    riskExecutionRating: "GOOD",
    disciplineRating: "MINOR_RUSH",
    whyEntered: "",
    playedAsExpected: true,
    expansionDescription: "",
    surpriseDescription: "",
    whatWentWrong: "",
    whatWentRight: "",
    institutionalLessons: "",
    howAffectsNext: "",
    followedTrinity: true,
    trinityViolationExplanation: "",
    correctKillzone: true,
    respectedHTFNarrative: true,
    waitedForInducement: true,
    managedRiskPerPlan: true,
    disciplineScore: "5",
    screenshots: [] as Id<"_storage">[],
    ...overrides,
  };
}

export function buildFormFromQuickLog(
  quick: QuickLogState,
  options?: { dailyBias?: string; accountId?: string; captures?: TradeCapture[] },
): Record<string, unknown> {
  const entry = Number(quick.entryPrice) || 0;
  const exit = Number(quick.exitPrice) || 0;
  const sl = Number(quick.stopLossPrice) || 0;
  const size = Number(quick.positionSize) || 1;
  const commission = Number(quick.commission) || 0;
  const pnl =
    entry && exit
      ? calculatePnlPreview(entry, exit, quick.direction, size, commission)
      : null;
  const rr = entry && sl && exit ? calculateRiskReward(entry, sl, exit, quick.direction) : null;
  const slPips = entry && sl ? calculateStopLossPips(entry, sl, quick.instrument) : null;

  const screenshotIds = options?.captures?.map((c) => c.storageId) ?? [];

  return getDefaultFormState({
    accountId: options?.accountId ?? "",
    instrument: quick.instrument,
    direction: quick.direction,
    session: quick.session,
    environment: quick.environment,
    entryPrice: quick.entryPrice,
    exitPrice: quick.exitPrice,
    stopLossPrice: quick.stopLossPrice,
    positionSize: quick.positionSize,
    commission: quick.commission,
    riskAmount: quick.riskAmount,
    whyEntered: quick.whyEntered,
    winLossStatus: quick.winLossStatus,
    dailyBias: options?.dailyBias ?? "NEUTRAL",
    pnl: pnl !== null ? String(pnl) : "",
    finalRR: rr !== null ? String(rr) : "",
    stopLossPips: slPips !== null ? String(slPips) : "5",
    target1RR: rr !== null ? String(Math.max(rr, 1)) : "3",
    tradeClosureReason: quick.exitPrice ? "MANUAL_EXIT" : "OPEN",
    screenshots: screenshotIds,
  });
}

export function buildFormFromTrade(trade: Doc<"trades">): Record<string, unknown> {
  return {
    accountId: trade.accountId || "",
    instrument: trade.instrument || "EUR/USD",
    direction: trade.direction || "LONG",
    entryPrice: String(trade.entryPrice ?? ""),
    exitPrice: String(trade.exitPrice ?? ""),
    positionSize: String(trade.positionSize ?? "0.01"),
    commission: String(trade.commission ?? "0"),
    environment: trade.environment || "DEMO",
    dailyBias: trade.dailyBias || "NEUTRAL",
    externalStructure: trade.externalStructure || "",
    majorLiquidityPools: trade.majorLiquidityPools || "",
    internalStructure: trade.internalStructure || "",
    currentRange: trade.currentRange || "",
    minorPushStatus: trade.minorPushStatus || "",
    session: trade.session || "LONDON",
    isInKillzone: trade.isInKillzone ?? true,
    poiType: trade.poiType || "EXTREME",
    poiQuality: trade.poiQuality || [],
    poiDescription: trade.poiDescription || "",
    gapSize: String(trade.gapSize ?? ""),
    inducementResting: trade.inducementResting || "",
    inducementType: trade.inducementType || "",
    distanceFromPoi: String(trade.distanceFromPoi ?? ""),
    liquidityPoolDescription: trade.liquidityPoolDescription || "",
    cleanBreak: trade.cleanBreak ?? false,
    breakSize: String(trade.breakSize ?? ""),
    trapSwept: trade.trapSwept || "NO",
    trapType: trade.trapType || "",
    trapLocation: String(trade.trapLocation ?? ""),
    trapTappedCount: String(trade.trapTappedCount ?? ""),
    trapCleanliness: trade.trapCleanliness || "",
    liquidityEngineering: trade.liquidityEngineering || "",
    liquidityTappedCount: String(trade.liquidityTappedCount ?? ""),
    retailBehavior: trade.retailBehavior || "",
    missingInducement: trade.missingInducement ?? false,
    ltfEntryTimeframe: trade.ltfEntryTimeframe || "5M",
    smcType: trade.smcType || "",
    smsAfterTrap: trade.smsAfterTrap ?? false,
    bmsPattern: trade.bmsPattern || "",
    bmsConfidence: String(trade.bmsConfidence ?? "5"),
    rtoApplicable: trade.rtoApplicable ?? false,
    rtoDistance: String(trade.rtoDistance ?? ""),
    entryConfidence: String(trade.entryConfidence ?? "5"),
    tradeModel: trade.tradeModel || "CONTINUATION",
    narrativeAlignment: trade.narrativeAlignment ?? true,
    tradingWithMainPush: trade.tradingWithMainPush ?? true,
    noNarrativeMisalignment: trade.noNarrativeMisalignment ?? true,
    clearLiquidityEngineering: trade.clearLiquidityEngineering || "UNCLEAR",
    institutionsReasoned: trade.institutionsReasoned ?? false,
    poiMitigationStatus: trade.poiMitigationStatus || "UNMITIGATED",
    approachDynamics: trade.approachDynamics || "",
    stopLossPrice: String(trade.stopLossPrice ?? ""),
    stopLossPlacement: trade.stopLossPlacement || "IFC_ABOVE",
    stopLossPips: String(trade.stopLossPips ?? "5"),
    stopLossQuality: trade.stopLossQuality || "CLEAN",
    riskAmount: String(trade.riskAmount ?? "10"),
    riskPercentage: String(trade.riskPercentage ?? "1"),
    target1RR: String(trade.target1RR ?? "3"),
    target2RR: String(trade.target2RR ?? "10"),
    target1Price: String(trade.target1Price ?? ""),
    target2Price: String(trade.target2Price ?? ""),
    timeInTradeMinutes: String(trade.timeInTradeMinutes ?? ""),
    maxProfitReached: String(trade.maxProfitReached ?? ""),
    maxDrawdown: String(trade.maxDrawdown ?? ""),
    target1Hit: trade.target1Hit ?? false,
    target1HitPrice: String(trade.target1HitPrice ?? ""),
    stopMovedToBE: trade.stopMovedToBE ?? false,
    timeToTarget1: String(trade.timeToTarget1 ?? ""),
    target2Status: trade.target2Status || "",
    target2ClosedAt: String(trade.target2ClosedAt ?? ""),
    finalRR: String(trade.finalRR ?? ""),
    timeToClose: String(trade.timeToClose ?? ""),
    breakEvenStopsMoved: trade.breakEvenStopsMoved ?? false,
    manualExit: trade.manualExit ?? false,
    manualExitReason: trade.manualExitReason || "",
    manualExitAligned: trade.manualExitAligned ?? false,
    tradeClosureReason: trade.tradeClosureReason || "OPEN",
    pnl: String(trade.pnl ?? ""),
    pnlPercentage: String(trade.pnlPercentage ?? ""),
    winLossStatus: trade.winLossStatus || "BREAK_EVEN",
    tradeQualityScore: String(trade.tradeQualityScore ?? "5"),
    poiQualityRating: trade.poiQualityRating || "ACCEPTABLE",
    inducementQualityRating: trade.inducementQualityRating || "CLEAR",
    trinityAlignmentRating: trade.trinityAlignmentRating || "ACCEPTABLE",
    riskExecutionRating: trade.riskExecutionRating || "GOOD",
    disciplineRating: trade.disciplineRating || "MINOR_RUSH",
    whyEntered: trade.whyEntered || "",
    playedAsExpected: trade.playedAsExpected ?? true,
    expansionDescription: trade.expansionDescription || "",
    surpriseDescription: trade.surpriseDescription || "",
    whatWentWrong: trade.whatWentWrong || "",
    whatWentRight: trade.whatWentRight || "",
    institutionalLessons: trade.institutionalLessons || "",
    howAffectsNext: trade.howAffectsNext || "",
    followedTrinity: trade.followedTrinity ?? true,
    trinityViolationExplanation: trade.trinityViolationExplanation || "",
    correctKillzone: trade.correctKillzone ?? true,
    respectedHTFNarrative: trade.respectedHTFNarrative ?? true,
    waitedForInducement: trade.waitedForInducement ?? true,
    managedRiskPerPlan: trade.managedRiskPerPlan ?? true,
    disciplineScore: String(trade.disciplineScore ?? "5"),
    screenshots: trade.screenshots || [],
  };
}

function num(v: unknown): number | undefined {
  if (v === "" || v === undefined || v === null) return undefined;
  const n = Number(v);
  return Number.isFinite(n) ? n : undefined;
}

function str(v: unknown): string | undefined {
  if (typeof v !== "string" || !v.trim()) return undefined;
  return v;
}

export function formToTradePayload(
  f: Record<string, unknown>,
  captures?: TradeCapture[],
): Record<string, unknown> {
  const screenshots = (f.screenshots as Id<"_storage">[]) ?? [];
  const captureIds = captures?.map((c) => c.storageId) ?? [];
  const mergedScreenshots = [...new Set([...screenshots, ...captureIds])];

  return {
    accountId: f.accountId && f.accountId !== "__none__" ? (f.accountId as Id<"accounts">) : undefined,
    instrument: f.instrument,
    direction: f.direction,
    entryPrice: Number(f.entryPrice),
    exitPrice: num(f.exitPrice),
    positionSize: Number(f.positionSize),
    commission: Number(f.commission),
    environment: f.environment,
    dailyBias: f.dailyBias,
    externalStructure: f.externalStructure,
    majorLiquidityPools: f.majorLiquidityPools,
    internalStructure: f.internalStructure,
    currentRange: str(f.currentRange),
    minorPushStatus: str(f.minorPushStatus),
    session: f.session,
    isInKillzone: f.isInKillzone,
    poiType: f.poiType,
    poiQuality: f.poiQuality,
    poiDescription: str(f.poiDescription),
    gapSize: num(f.gapSize),
    inducementResting: str(f.inducementResting),
    inducementType: str(f.inducementType),
    distanceFromPoi: num(f.distanceFromPoi),
    liquidityPoolDescription: str(f.liquidityPoolDescription),
    cleanBreak: f.cleanBreak || undefined,
    breakSize: num(f.breakSize),
    trapSwept: f.trapSwept,
    trapType: str(f.trapType),
    trapLocation: num(f.trapLocation),
    trapTappedCount: num(f.trapTappedCount),
    trapCleanliness: str(f.trapCleanliness),
    liquidityEngineering: str(f.liquidityEngineering),
    liquidityTappedCount: num(f.liquidityTappedCount),
    retailBehavior: str(f.retailBehavior),
    missingInducement: f.missingInducement,
    ltfEntryTimeframe: str(f.ltfEntryTimeframe),
    smcType: str(f.smcType),
    smsAfterTrap: f.smsAfterTrap,
    bmsPattern: str(f.bmsPattern),
    bmsConfidence: Number(f.bmsConfidence),
    rtoApplicable: f.rtoApplicable,
    rtoDistance: num(f.rtoDistance),
    entryConfidence: Number(f.entryConfidence),
    tradeModel: f.tradeModel,
    narrativeAlignment: f.narrativeAlignment,
    tradingWithMainPush: f.tradingWithMainPush,
    noNarrativeMisalignment: f.noNarrativeMisalignment,
    clearLiquidityEngineering: str(f.clearLiquidityEngineering),
    institutionsReasoned: f.institutionsReasoned || undefined,
    poiMitigationStatus: f.poiMitigationStatus,
    approachDynamics: str(f.approachDynamics),
    stopLossPrice: Number(f.stopLossPrice),
    stopLossPlacement: f.stopLossPlacement,
    stopLossPips: Number(f.stopLossPips),
    stopLossQuality: f.stopLossQuality,
    riskAmount: Number(f.riskAmount),
    riskPercentage: Number(f.riskPercentage),
    target1RR: Number(f.target1RR),
    target2RR: Number(f.target2RR),
    target1Price: num(f.target1Price),
    target2Price: num(f.target2Price),
    timeInTradeMinutes: num(f.timeInTradeMinutes),
    maxProfitReached: num(f.maxProfitReached),
    maxDrawdown: num(f.maxDrawdown),
    target1Hit: f.target1Hit || undefined,
    target1HitPrice: num(f.target1HitPrice),
    stopMovedToBE: f.stopMovedToBE || undefined,
    timeToTarget1: num(f.timeToTarget1),
    target2Status: str(f.target2Status),
    target2ClosedAt: num(f.target2ClosedAt),
    finalRR: num(f.finalRR),
    timeToClose: num(f.timeToClose),
    breakEvenStopsMoved: f.breakEvenStopsMoved || undefined,
    manualExit: f.manualExit || undefined,
    manualExitReason: str(f.manualExitReason),
    manualExitAligned: f.manualExitAligned || undefined,
    tradeClosureReason: f.tradeClosureReason,
    pnl: num(f.pnl),
    pnlPercentage: num(f.pnlPercentage),
    winLossStatus: f.winLossStatus,
    tradeQualityScore: Number(f.tradeQualityScore),
    poiQualityRating: f.poiQualityRating,
    inducementQualityRating: f.inducementQualityRating,
    trinityAlignmentRating: f.trinityAlignmentRating,
    riskExecutionRating: f.riskExecutionRating,
    disciplineRating: f.disciplineRating,
    whyEntered: str(f.whyEntered),
    playedAsExpected: f.playedAsExpected,
    expansionDescription: str(f.expansionDescription),
    surpriseDescription: str(f.surpriseDescription),
    whatWentWrong: str(f.whatWentWrong),
    whatWentRight: str(f.whatWentRight),
    institutionalLessons: str(f.institutionalLessons),
    howAffectsNext: str(f.howAffectsNext),
    followedTrinity: f.followedTrinity,
    trinityViolationExplanation: str(f.trinityViolationExplanation),
    correctKillzone: f.correctKillzone,
    respectedHTFNarrative: f.respectedHTFNarrative,
    waitedForInducement: f.waitedForInducement,
    managedRiskPerPlan: f.managedRiskPerPlan,
    disciplineScore: Number(f.disciplineScore),
    captures: captures?.length ? captures : undefined,
    screenshots: mergedScreenshots.length > 0 ? mergedScreenshots : undefined,
  };
}

export function quickLogToPayload(
  quick: QuickLogState,
  options?: { dailyBias?: string; accountId?: Id<"accounts">; captures?: TradeCapture[] },
): Record<string, unknown> {
  const form = buildFormFromQuickLog(quick, {
    dailyBias: options?.dailyBias,
    accountId: options?.accountId ? String(options.accountId) : undefined,
    captures: options?.captures,
  });
  return formToTradePayload(form, options?.captures);
}
